default:
  batchmode: false
  cachedb: "sqlite"
  googleuser: ""
  paths:
    cachedir: "cache"
    scratchdir: "/tmp/scratch"
  plot: true
  slackchannel: ""

production:
  batchmode: true
  plot: false
